export const productsData = [
  {
    id: 1,
    categoryId: 1,
    title: '1 Product Name Goes Here',
    shortDescription: 'Volup erat ipsum diam elitr rebum et dolor. Est nonumy elitr erat diam stet sit clita ea. Sanc ipsum et, labore clita lorem magna duo dolor no sea Nonumy',
    description: 'Eos no lorem eirmod diam diam, eos elitr et gubergren diam sea. Consetetur vero aliquyam invidunt duo dolores et duo sit. Vero diam ea vero et dolore rebum, dolor rebum eirmod consetetur invidunt sed sed et, lorem duo et eos elitr, sadipscing kasd ipsum rebum diam. Dolore diam stet rebum sed tempor kasd eirmod. Takimata kasd ipsum accusam sadipscing, eos dolores sit no ut diam consetetur duo justo est, sit sanctus diam tempor aliquyam eirmod nonumy rebum dolor accusam, ipsum kasd eos consetetur at sit rebum, diam kasd invidunt tempor lorem, ipsum lorem elitr sanctus eirmod takimata dolor ea invidunt.',
    image: [{i: 1, p: '/img/product-1.jpg'}, {i: 2, p: '/img/product-9.jpg'}],
    color: 'Black',
    sizes: null,
    price: '100.05',
    priceLow: null,
    reviews: [{
      reviewId: 1,
      image: '/img/user.jpg',
      date: 1683909112461,
      rating: 5,
      user: 'Roma',
      message: 'Roma amet duo labore stet elitr ea clita ipsum, tempor labore accusam ipsum et no at. Kasd diam tempor rebum magna dolores sed sed eirmod ipsum.',
    }],
  },
  {
    id: 2,
    categoryId: 1,
    title: '2 Product Name Goes Here',
    shortDescription: 'Volup erat ipsum diam elitr rebum et dolor. Est nonumy elitr erat diam stet sit clita ea. Sanc ipsum et, labore clita lorem magna duo dolor no sea Nonumy',
    description: 'Eos no lorem eirmod diam diam, eos elitr et gubergren diam sea. Consetetur vero aliquyam invidunt duo dolores et duo sit. Vero diam ea vero et dolore rebum, dolor rebum eirmod consetetur invidunt sed sed et, lorem duo et eos elitr, sadipscing kasd ipsum rebum diam. Dolore diam stet rebum sed tempor kasd eirmod. Takimata kasd ipsum accusam sadipscing, eos dolores sit no ut diam consetetur duo justo est, sit sanctus diam tempor aliquyam eirmod nonumy rebum dolor accusam, ipsum kasd eos consetetur at sit rebum, diam kasd invidunt tempor lorem, ipsum lorem elitr sanctus eirmod takimata dolor ea invidunt.',
    image: [{i:1, p:'/img/product-2.jpg'}],
    color: 'Blue',
    sizes: [{i:1,s:'M'}, {i:2,s:'L'}],
    price: '400.00',
    priceLow: '390.00',
    reviews: [],
  },
  {
    id: 3,
    categoryId: 2,
    title: '3 Product Name Goes Here',
    shortDescription: 'Volup erat ipsum diam elitr rebum et dolor. Est nonumy elitr erat diam stet sit clita ea. Sanc ipsum et, labore clita lorem magna duo dolor no sea Nonumy',
    description: 'Eos no lorem eirmod diam diam, eos elitr et gubergren diam sea. Consetetur vero aliquyam invidunt duo dolores et duo sit. Vero diam ea vero et dolore rebum, dolor rebum eirmod consetetur invidunt sed sed et, lorem duo et eos elitr, sadipscing kasd ipsum rebum diam. Dolore diam stet rebum sed tempor kasd eirmod. Takimata kasd ipsum accusam sadipscing, eos dolores sit no ut diam consetetur duo justo est, sit sanctus diam tempor aliquyam eirmod nonumy rebum dolor accusam, ipsum kasd eos consetetur at sit rebum, diam kasd invidunt tempor lorem, ipsum lorem elitr sanctus eirmod takimata dolor ea invidunt.',
    image: [{i:1, p:'/img/product-3.jpg'}],
    color: 'White',
    sizes: null,
    price: '200.00',
    priceLow: '190.00',
    reviews: [{
      reviewId: 1,
      image: '/img/user.jpg',
      date: 1683909112461,
      rating: 5,
      user: 'Dima',
      message: 'Dima amet duo labore stet elitr ea clita ipsum, tempor labore accusam ipsum et no at. Kasd diam tempor rebum magna dolores sed sed eirmod ipsum.',
    }],
  },
  {
    id: 4,
    categoryId: 3,
    title: '4 Product Name Goes Here',
    shortDescription: 'Volup erat ipsum diam elitr rebum et dolor. Est nonumy elitr erat diam stet sit clita ea. Sanc ipsum et, labore clita lorem magna duo dolor no sea Nonumy',
    description: 'Eos no lorem eirmod diam diam, eos elitr et gubergren diam sea. Consetetur vero aliquyam invidunt duo dolores et duo sit. Vero diam ea vero et dolore rebum, dolor rebum eirmod consetetur invidunt sed sed et, lorem duo et eos elitr, sadipscing kasd ipsum rebum diam. Dolore diam stet rebum sed tempor kasd eirmod. Takimata kasd ipsum accusam sadipscing, eos dolores sit no ut diam consetetur duo justo est, sit sanctus diam tempor aliquyam eirmod nonumy rebum dolor accusam, ipsum kasd eos consetetur at sit rebum, diam kasd invidunt tempor lorem, ipsum lorem elitr sanctus eirmod takimata dolor ea invidunt.',
    image: [{i:1, p:'/img/product-4.jpg'}],
    color: 'Black',
    sizes: [{i:1,s:36}, {i:2,s:38}, {i:3,s:40}],
    price: '250.00',
    priceLow: '240.00',
    reviews: [{
      reviewId: 1,
      image: '/img/user.jpg',
      date: 1683909112461,
      rating: 5,
      user: 'Roma',
      message: 'Roma amet duo labore stet elitr ea clita ipsum, tempor labore accusam ipsum et no at. Kasd diam tempor rebum magna dolores sed sed eirmod ipsum.',
    }],
  },
  {
    id: 5,
    categoryId: 4,
    title: '5 Product Name Goes Here',
    shortDescription: 'Volup erat ipsum diam elitr rebum et dolor. Est nonumy elitr erat diam stet sit clita ea. Sanc ipsum et, labore clita lorem magna duo dolor no sea Nonumy',
    description: 'Eos no lorem eirmod diam diam, eos elitr et gubergren diam sea. Consetetur vero aliquyam invidunt duo dolores et duo sit. Vero diam ea vero et dolore rebum, dolor rebum eirmod consetetur invidunt sed sed et, lorem duo et eos elitr, sadipscing kasd ipsum rebum diam. Dolore diam stet rebum sed tempor kasd eirmod. Takimata kasd ipsum accusam sadipscing, eos dolores sit no ut diam consetetur duo justo est, sit sanctus diam tempor aliquyam eirmod nonumy rebum dolor accusam, ipsum kasd eos consetetur at sit rebum, diam kasd invidunt tempor lorem, ipsum lorem elitr sanctus eirmod takimata dolor ea invidunt.',
    image: [{i:1, p:'/img/product-5.jpg'}],
    color: 'White',
    sizes: null,
    price: '200.00',
    priceLow: '190.00',
    reviews: [{
      reviewId: 1,
      image: '/img/user.jpg',
      date: 1683909112461,
      rating: 4,
      user: 'Dima',
      message: 'Dima amet duo labore stet elitr ea clita ipsum, tempor labore accusam ipsum et no at. Kasd diam tempor rebum magna dolores sed sed eirmod ipsum.',
    },
    {
      reviewId: 2,
      image: '/img/user.jpg',
      date: 1683909112461,
      rating: 4,
      user: 'Roma',
      message: 'Roma amet duo labore stet elitr ea clita ipsum, tempor labore accusam ipsum et no at. Kasd diam tempor rebum magna dolores sed sed eirmod ipsum.',
    }],
  },
];

export const categoriesData = [
  {
    id: 1,
    title: 'Health & Personal Care',
    image: '/img/cat-1.jpg',
    path: '/health-personal-care',
    quantity: productsData.filter(item => item.categoryId === 1).length,
  },
  {
    id: 2,
    title: 'Beauty picks',
    image: '/img/cat-2.jpg',
    path: '/beauty-picks',
    quantity: productsData.filter(item => item.categoryId === 2).length,
  },
  {
    id: 3,
    title: 'Dresses',
    image: '/img/cat-3.jpg',
    path: '/dresses',
    quantity: productsData.filter(item => item.categoryId === 3).length,
  },
  {
    id: 4,
    title: 'Electronics',
    image: '/img/cat-4.jpg',
    path: '/electronics',
    quantity: productsData.filter(item => item.categoryId === 4).length,
  },
  {
    id: 5,
    title: 'Discover fashion trends',
    image: '/img/cat-5.jpg',
    path: '/discover-fashion-trends',
    quantity: productsData.filter(item => item.categoryId === 5).length,
  },
  {
    id: 6,
    title: 'Shop activity trackers',
    image: '/img/cat-6.jpg',
    path: '/trackers-and-smartwatches',
    quantity: productsData.filter(item => item.categoryId === 6).length,
  },
  {
    id: 7,
    title: 'Home refresh ideas',
    image: '/img/cat-7.jpg',
    path: '/home-refresh-ideas',
    quantity: productsData.filter(item => item.categoryId === 7).length,
  },
  {
    id: 8,
    title: 'Spring new arrivals',
    image: '/img/cat-8.jpg',
    path: '/spring-new-arrivals',
    quantity: productsData.filter(item => item.categoryId === 8).length,
  },
  {
    id: 9,
    title: 'Create with strip lights',
    image: '/img/cat-9.jpg',
    path: '/create-with-strip-lights',
    quantity: productsData.filter(item => item.categoryId === 9).length,
  },
  {
    id: 10,
    title: 'For your Fitness Needs',
    image: '/img/cat-10.jpg',
    path: '/for-your-fitness-needs',
    quantity: productsData.filter(item => item.categoryId === 10).length,
  },
  {
    id: 11,
    title: 'Shop Laptops & Tablets',
    image: '/img/cat-11.jpg',
    path: '/shop-laptops-tablets',
    quantity: productsData.filter(item => item.categoryId === 11).length,
  },
  {
    id: 12,
    title: 'Shop Pet supplies',
    image: '/img/cat-12.jpg',
    path: '/shop-pet-supplies',
    quantity: productsData.filter(item => item.categoryId === 12).length,
  },
]

export const productsCartData = []

export const productsOrderData = []